# Generated by Django 5.0.1 on 2024-01-25 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_child_of_alter_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='child_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task'),
        ),
    ]
